image: node:lts

stages:
  - deploy

staging:
  stage: deploy
  script:
    - curl -fsSL https://get.deta.dev/cli.sh | sh
    - /root/.deta/bin/deta deploy
  cache:
    key: lettercms-resize
    paths:
      - .deta
      - deta.json
  environment:
    name: staging
    url: https://lettercms-resize.deta.sh
  only:
    - main
