image: node:lts

stages:
  - deploy

staging:
  stage: deploy
  script:
    - curl -fsSL https://get.deta.dev/cli.sh | sh
    - deta deploy
  environment:
    name: staging
    url: https://lettercms-resize.deta.sh
  only:
    - main
